### ISSUE TITLE
EPROTO err and early close connect before electrumx cxn

### ISSUE THREAD

**Issue by ch4ot1c** [BSHA3/bsha3-rpc-explorer#13]
Running alongside and `electrumx` instance (and full-node):
```
0|npm      | Running RPC Explorer for BSHA3
0|npm      | Connecting via RPC to node at localhost:8334
0|npm      | Connecting to ElectrumX Server: 127.0.0.1:50001
0|npm      | OnError:Error: write EPROTO 139876711077696:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
0|npm      | 
0|npm      | OnClose:undefined
0|npm      | Request Error: Error: close connect, method=server.version, params=bsha3-rpc-explorer-v1.1,1.2
0|npm      | Error: close connect
0|npm      |     at Object.keys.forEach (/home/ubuntu/bsha3-rpc-explorer/node_modules/electrum-client/lib/client.js:90:46)
0|npm      |     at Array.forEach (<anonymous>)
0|npm      |     at ElectrumClient.onClose (/home/ubuntu/bsha3-rpc-explorer/node_modules/electrum-client/lib/client.js:89:50)
0|npm      |     at ElectrumClient.onClose (/home/ubuntu/bsha3-rpc-explorer/node_modules/electrum-client/lib/electrum_client.js:42:15)
0|npm      |     at TLSSocket.conn.on (/home/ubuntu/bsha3-rpc-explorer/node_modules/electrum-client/lib/init_socket.js:34:14)
0|npm      |     at TLSSocket.emit (events.js:187:15)
0|npm      |     at _handle.close (net.js:611:12)
0|npm      |     at TCP.done (_tls_wrap.js:384:7)
0|npm      | Connected to ElectrumX Server: 127.0.0.1:50001, versions: null
0|npm      | Live with ElectrumX API.
0|npm      | Unable to get exchange rate data
```

**Comment by ch4ot1c** [comment]
Opened 50001 with ufw, now:
```
0|npm  | tryCache: getBlockchainInfo, 10000
0|npm  | Request Error: [object Object], method=blockchain.scripthash.get_balance, params=0eb4e334d070a5edcadaa98d35f059c1027b1e60c29ecafb831c92b0b9ffe28a112c0b6061dfd68b85c1544414f7e8b120b323af383e441515dbf1f1710d8ca6
0|npm  | { code: 1,
0|npm  |   message:
0|npm  |    '0eb4e334d070a5edcadaa98d35f059c1027b1e60c29ecafb831c92b0b9ffe28a112c0b6061dfd68b85c1544414f7e8b120b323af383e441515dbf1f1710d8ca6 is not a valid script hash' }
0|npm  | Request Error: [object Object], method=blockchain.scripthash.get_history, params=0eb4e334d070a5edcadaa98d35f059c1027b1e60c29ecafb831c92b0b9ffe28a112c0b6061dfd68b85c1544414f7e8b120b323af383e441515dbf1f1710d8ca6
0|npm  | { code: 1,
0|npm  |   message:
0|npm  |    '0eb4e334d070a5edcadaa98d35f059c1027b1e60c29ecafb831c92b0b9ffe28a112c0b6061dfd68b85c1544414f7e8b120b323af383e441515dbf1f1710d8ca6 is not a valid script hash' }
0|npm  | { result: null, server: '127.0.0.1' }
0|npm  | TypeError: Cannot read property 'length' of null
0|npm  |     at /home/ubuntu/bsha3-rpc-explorer/routes/baseActionsRouter.js:617:44
0|npm  |     at process.internalTickCallback (internal/process/next_tick.js:77:7)
0|npm  | GET /address/ceJB3SirEaMHQXgfhxnNhxhWAPpxTZQSwu 500 1002.595 ms - 14528
```

**Comment by ch4ot1c** [comment]
Resolved; needed to add outputLength, else was sha3-512: `sha3(x, { outputLength: 256})`
