### ISSUE TITLE
Error: Cannot find module 'crypto-js/sha256'

### ISSUE THREAD

**Issue by interbiznw** [BSHA3/bsha3-rpc-explorer#5]
Error: Cannot find module 'crypto-js/sha256'

```

root@pool:~/bsha3-rpc-explorer# npm start                                                                                                                                                                                       [114/692]

> bsha3-rpc-explorer@1.0.0 start /root/bsha3-rpc-explorer
> node ./bin/www

module.js:550
    throw err;
    ^

Error: Cannot find module 'crypto-js/sha256'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/bsha3-rpc-explorer/routes/baseActionsRouter.js:8:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/bsha3-rpc-explorer/app.js:30:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bsha3-rpc-explorer@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bsha3-rpc-explorer@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-04T01_21_21_695Z-debug.log
```

**Comment by ch4ot1c** [comment]
Fixed - crypto-js branch `3.1.9` needed to be the base instead of `master`
